In [1]:
import numpy as np
import matplotlib

import matplotlib.pyplot as plt

import matplotlib.pyplot as figure

from sklearn.preprocessing import StandardScaler
import pandas as pd
import os
from sklearn import preprocessing
from random import sample
import glob, os 
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets.samples_generator import make_blobs
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import roc_curve, auc,roc_auc_score
from sklearn.metrics import confusion_matrix
from scipy.sparse import hstack
from random import sample
from collections import Counter
import pickle

In [2]:
all_files = glob.glob(os.path.join('testDatanotbelongToClusters/', "*.csv"))     

df_from_each_file =  (pd.read_csv(f).sample(10000) for f in all_files)

In [3]:
positiveSamples  = pd.concat(df_from_each_file, ignore_index=True)

In [6]:
positiveSamples = positiveSamples.drop(['bigram_pref', 'label'], axis = 1)

In [7]:
positiveSamples.head()

,prefix,pref_len,domain,bigramPref
0,prdadmin.www.buildingowners,27,withairbnb.com_Jul5,^prdadmin.www.buildingowners$
1,qh.host-dev,11,withairbnb.com_Jul5,^qh.host-dev$
2,test3www.sweden-stage,21,withairbnb.com_Jul5,^test3www.sweden-stage$
3,fbnewsroomko.multifamily,24,withairbnb.com_Jul5,^fbnewsroomko.multifamily$
4,nobody.hostadvance-reg,22,withairbnb.com_Jul5,^nobody.hostadvance-reg$

In [26]:
prefixesData = positiveSamples[['bigramPref', 'pref_len']]

In [27]:
prefixesData.head()

                      bigramPref  pref_len
0  ^prdadmin.www.buildingowners$        27
1                  ^qh.host-dev$        11
2        ^test3www.sweden-stage$        21
3     ^fbnewsroomko.multifamily$        24
4       ^nobody.hostadvance-reg$        22

In [28]:
file = open('vectorizer', 'rb')
vectorizer = pickle.load(file)

In [29]:
prefixesSet = vectorizer.transform(prefixesData['bigramPref'])

In [30]:
combined_test_X = hstack((prefixesSet,np.array(prefixesData['pref_len'])[:,None])).tocsr()

In [31]:
prefixesTestSet = pd.DataFrame(combined_test_X.toarray())

In [32]:
prefixesTestSet.head()

,0,1,2,3,4,5,6,7,8,9,...,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,27
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,21
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,24
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,22

In [33]:
prefixesTestSet.to_csv("prefixesTestSet.csv", index = False)